config/routes.rb
Rails.application.routes.draw do
 

  resources :recipes do
    resources :ingredients
  end
  get 'welcome/index'
  get 'about/index'

   root 'welcome#index'

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	has_many :ingredients, dependent: :destroy 
	validates :name, presence: true, 
					 length: {minimum: 5}
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
  def show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
	def create
	    @recipe = Recipe.find(params[:recipe_id])
	    @ingredient = @recipe.ingredients.create(ingredient_params)
	    redirect_to recipe_path(@recipe)
	end

	def destroy
	  	@recipe = Recipe.find(params[:ingredient_id])
	  	@ingredient = @recipe.ingredients.find(params[:id])
	    @ingredient.destroy
	    redirect_to recipe_path(@recipe)
	end
 
  private
    def ingredient_params
      params.require(:ingredient).permit(:name, :description)
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
def index
		@recipes = Recipe.all
	end

	def show
		@recipe = Recipe.find(params[:id])
	end

	def new 
		@recipe = Recipe.new
	end

	def edit
		@recipe = Recipe.find(params[:id])
	end

	def create
		@recipe = Recipe.new(recipe_params)
		if @recipe.save
			redirect_to @recipe
		else
			render 'new'
		end 
	end

	def update
		@recipe = Recipe.find(params[:id])

		if @recipe.update(recipe_params)
			redirect_to @recipe
		else
			render 'edit'
		end
	end

	def destroy
		@recipe = Recipe.find(params[:id])
		@recipe.destroy

		redirect_to recipes_path
	end
	
	private
	def recipe_params
		params.require(:recipe).permit(:name, :description)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def nav_bar
	  content_tag(:ul, class: "nav navbar-nav") do
	      yield
	  end
	end

	def nav_link(text, path)
		options = current_page?(path) ? { class: "active" } : {}
		content_tag(:li, options) do
			link_to text, path
		end
	end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about/index.html.erb
<h1>About#index</h1>
<p>Find me in app/views/about/index.html.erb</p>

app/views/about/show.html.erb
<div id="aboutleft">
<h2>About <span class="blue">My Recipes</span></h2>
<p>We're YOUR recipies, so let us bring you the tool that you need to keep, organize and share your recipies.</p>
</div>

app/views/ingredients/_form.html.erb
<%= form_for([@recipe, @recipe.ingredients.build]) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/ingredients/_ingredient.html.erb
<p>
  <strong>Ingredient:</strong>
  <%= ingredient.name %>
</p>
 
<p>
  <strong>Description:</strong>
  <%= ingredient.description %>
</p>

<p>
	<%= link_to 'Delete Ingredient', [recipe.ingredient, recipe],
				method: :delete,
				data: {confirm: 'Are you sure?'} %>
</p>

app/views/ingredients/index.html.erb
<h1>Listing ingredients</h1>

<%= link_to 'New Ingredient', new_ingredient_path %>
<table border=1>
  <tr>
    <th>Name</th>
    <th>description</th>
  </tr>
 
  <% @ingredients.each do |ingredient| %>
    <tr>
      <td><%= ingredient.name %></td>
      <td><%= ingredient.description %></td>
      <td><%= link_to 'Show', ingredient_path(ingredient) %></td>
      <td><%= link_to 'Edit', edit_ingredient_path(ingredient) %></td>
      <td><%= link_to 'destroy', ingredient_path(ingredient),
              method: :delete,
              data: {confirm: 'are you sure?'} %></td>
    </tr>
  <% end %>
</table>

app/views/ingredients/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @ingredient.name %>
</p>
 
<p>
  <strong>Description:</strong>
  <%= @ingredient.description %>
</p>
<%= link_to 'Edit', edit_ingredient_path(@ingredient) %> |
<%= link_to 'Back', ingredients_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyRecipes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%# this code is for the web header and menu-%>
<nav class="navbar navbar-default navbar-fixed-top">
<div class="navbar-header">
  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>

    <%#<img src="assets/logo.png" alt="" class="logo">-%>
    <a class="navbar-brand" >MyRecipes <span class="Italyc"> Share you'r taste for the world</span>...</a>
</div>
 <div id="navbar" class="navbar-collapse collapse">
    <%= nav_bar do %>
     <%= nav_link 'Welcome', root_path %>
     <%= nav_link 'Recipes', recipes_path %>
     <%= nav_link 'About', 'about/index' %>
     <% end %>
 </div>
</nav>
<%# ends for the web header and menu-%>
<aside id="maincontent" class="bodywidth clear">

    <%= yield %>

</aside>

</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>
 
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@recipe.errors.count, "error") %> prohibited
        this recipe from being saved:
      </h2>
      <ul>
        <% @recipe.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :desciption %><br>
    <%= f.text_area :description %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/recipes/edit.html.erb
<div id="aboutleft">
<h1>Editing recipe</h1>
<%= render 'form' %> 
<%= link_to 'Back', recipes_path %>
</div>

app/views/recipes/index.html.erb
<div id="aboutleft">
<h1>Listing recipes</h1>

<%= link_to 'New Recipe', new_recipe_path %>
<table border=1>
  <tr>
    <th>Name</th>
    <th>description</th>
  </tr>
 
  <% @recipes.each do |recipe| %>
    <tr>
      <td><%= recipe.name %></td>
      <td><%= recipe.description %></td>
      <td><%= link_to 'Show', recipe_path(recipe) %></td>
      <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
      <td><%= link_to 'destroy', recipe_path(recipe),
              method: :delete,
              data: {confirm: 'are you sure?'} %></td>
    </tr>
  <% end %>
</table>
</div>

app/views/recipes/new.html.erb
<div id="aboutleft">
<h1>New Recipe</h1>
  
  <%= render 'form' %>
  <%= link_to 'Back', recipes_path %>
</div>

app/views/recipes/show.html.erb
<div id="aboutleft">
<h1>
  
  <strong><%= @recipe.name %></strong>
</h1>
 
<p>
  <strong>Description:</strong>
  <%= @recipe.description %>
</p>

<h2>Ingredients</h2>
<%= render @recipe.ingredients %>


<h2>Add a ingredient:</h2>
<%= render 'ingredients/form'%>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>
</div>

app/views/welcome/index.html.erb
<div id="aboutleft">
<h2>Welcome to <span class="blue">my recipes</span></h2>
<p>Find all your recipes and share them within the world.</p>
</div>